version: '3.8'
services:
  mondial-web:
    build: .
    ports:
      - "5173:5173"  # Puerto de Vite
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - CHOKIDAR_USEPOLLING=true  # Mejora detección de cambios en Docker

# Construir la imagen y levantar el contenedor
# docker-compose up -d

# Detener y eliminar el contenedor
# docker-compose down

# Si se modifica el Dockerfile o docker-compose.yml, reconstruir
# docker-compose up -d --build

# Ver los logs del contenedor
# docker-compose logs -f